try{
    console.log("hello");
    console.log(a);
}
catch(err){
    console.log("error handle",err);
}
finally{
    console.log("finallt block will always exexcuted");
}